//
//  PilatesExercises.swift
//  Apex Pilates
//
//  Created by Dennis Dang on 4/29/20.
//  Copyright © 2020 dlab. All rights reserved.
//

import Foundation


let matExercises = [
    (name: "The Hundred", type: "mat"),
    (name: "Roll Up", type:"mat"),
    (name: "Roll Over", type:"mat"),
    (name: "Single Leg Circles", type:"mat"),
    (name: "Rolling Like a Ball", type:"mat"),
    (name: "Single Leg Stretch", type:"mat"),
    (name: "Double Leg Stretch", type:"mat"),
    (name: "Spine Stretch Forward", type:"mat"),
    (name: "Open Leg Rocker", type:"mat"),
    (name: "Corkscrew", type:"mat"),
    (name: "Saw", type:"mat"),
    (name: "Swan", type:"mat"),
    (name: "Single Leg Kicks", type:"mat"),
    (name: "Double Leg Kicks", type:"mat"),
    (name: "Neck Pull", type:"mat"),
    (name: "High Scissors", type:"mat"),
    (name: "High Bicycle", type:"mat"),
    (name: "Shoulder Bridge", type:"mat"),
    (name: "Spine", type:"mat"),
    (name: "Twist", type:"mat"),
    (name: "Jackknife", type:"mat"),
    (name: "Side Kick Series - Front/Back", type:"mat"),
    (name: "Teaser 1", type:"mat"),
    (name: "Teaser 2", type:"mat"),
    (name: "Teaser 3", type:"mat"),
    (name: "Hip Circles", type:"mat"),
    (name: "Swimming", type:"mat"),
    (name: "Leg Pull Front (Down)", type:"mat"),
    (name: "Leg Pull Back (Up)", type:"mat"),
    (name: "Kneeling Side Kicks", type:"mat"),
    (name: "Side Bend", type:"mat"),
    (name: "Boomerang", type:"mat"),
    (name: "Seal Crab", type:"mat"),
    (name: "Rocking", type:"mat"),
    (name: "Balance Control - Roll Over", type:"mat"),
    (name: "Push Ups", type:"mat")
]

let reformerExercises = [
    (name: "Footwork - Toes", type: "reformer"),
    (name: "Footwork - Arches", type: "reformer"),
    (name: "Footwork - Heels", type: "reformer"),
    (name: "Footwork - Heels lowering", type: "reformer"),
    (name: "Hundred", type: "reformer"),
    (name: "Overhead", type: "reformer"),
    (name: "Coordination", type: "reformer"),
    (name: "Rowing - Into the Sternum", type: "reformer"),
    (name: "Rowing - 90 Degrees", type: "reformer"),
    (name: "Rowing - From the Chest", type: "reformer"),
    (name: "Rowing - From the Hips", type: "reformer"),
    (name: "Rowing - Shaving", type: "reformer"),
    (name: "Rowing - Hug", type: "reformer"),
    (name: "Long Box - Pull Straps", type: "reformer"),
    (name: "Long Box - T Straps", type: "reformer"),
    (name: "Long Box - Backstroke", type: "reformer"),
    (name: "Long Box - Teaser", type: "reformer"),
    (name: "Long Box - Breaststroke", type: "reformer"),
    (name: "Long Box - Horseback", type: "reformer"),
    (name: "Long Stretch - Long Stretch", type: "reformer"),
    (name: "Long Stretch - Down Stretch", type: "reformer"),
    (name: "Long Stretch - Up Stretch", type: "reformer"),
    (name: "Long Stretch - Elephant", type: "reformer"),
    (name: "Long Stretch - Elephant One Leg Back", type: "reformer"),
    (name: "Long Stretch - Long Back Stretch", type: "reformer"),
    (name: "Stomach Massage - Round", type: "reformer"),
    (name: "Stomach Massage - Hands Back", type: "reformer"),
    (name: "Stomach Massage - Reach Up", type: "reformer"),
    (name: "Stomach Massage - Twist", type: "reformer"),
    (name: "Short Box - Round Back", type: "reformer"),
    (name: "Short Box - Flat Back", type: "reformer"),
    (name: "Short Box - Side to Side", type: "reformer"),
    (name: "Short Box - Twist", type: "reformer"),
    (name: "Short Box - Around the World", type: "reformer"),
    (name: "Short Box - Tree", type: "reformer"),
    (name: "Short Spine Massage", type: "reformer"),
    (name: "Semi Circle", type: "reformer"),
    (name: "Chest Expansion", type: "reformer"),
    (name: "Thigh Stretch", type: "reformer"),
    (name: "Arm Circles", type: "reformer"),
    (name: "Snake Twist", type: "reformer"),
    (name: "Corkscrew", type: "reformer"),
    (name: "Tick Tock", type: "reformer"),
    (name: "Balance Control Step Off", type: "reformer"),
    (name: "Long Spine Massage", type: "reformer"),
    (name: "Feet in Straps - Frogs", type: "reformer"),
    (name: "Feet in Straps - Leg Circles", type: "reformer"),
    (name: "Knee Stretch - Round", type: "reformer"),
    (name: "Knee Stretch - Arched", type: "reformer"),
    (name: "Knee Stretch - Knees Off", type: "reformer"),
    (name: "Running", type: "reformer"),
    (name: "Pelvic Lift", type: "reformer"),
    (name: "Push Up Front", type: "reformer"),
    (name: "Push Up Back", type: "reformer"),
    (name: "Side Splits", type: "reformer"),
    (name: "Front Splits", type: "reformer"),
    (name: "Russian Splits", type: "reformer")
]

let cadillacExercises = [
    (name: "Rollback Bar - Roll Down", type: "cadillac"),
    (name: "Rollback Bar - One Arm Roll Down", type: "cadillac"),
    (name: "Leg Springs - Circles", type: "cadillac"),
    (name: "Leg Springs - Walking", type: "cadillac"),
    (name: "Leg Springs - Beats", type: "cadillac"),
    (name: "Leg Springs - Bicycle", type: "cadillac"),
    (name: "Leg Springs - Small Circles", type: "cadillac"),
    (name: "Leg Springs - Frogs -In the Air", type: "cadillac"),
    (name: "Leg Springs - Circles -In the Air", type: "cadillac"),
    (name: "Leg Springs - Walking -In the Air", type: "cadillac"),
    (name: "Leg Springs - Beats -In the Air", type: "cadillac"),
    (name: "Leg Springs - Bicycle", type: "cadillac"),
    (name: "Leg Springs - Airplane", type: "cadillac"),
    (name: "Side Leg Springs - Front/Back", type: "cadillac"),
    (name: "Side Leg Springs - Up/Down", type: "cadillac"),
    (name: "Side Leg Springs - Small Circles", type: "cadillac"),
    (name: "Side Leg Springs - Big Circles", type: "cadillac"),
    (name: "Side Leg Springs - Bicycle", type: "cadillac"),
    (name: "Arm Springs - Flying Eagle", type: "cadillac"),
    (name: "Arm Springs - Press Down", type: "cadillac"),
    (name: "Arm Springs - Circles", type: "cadillac"),
    (name: "Arm Springs - Triceps", type: "cadillac"),
    (name: "Push Thru Bar - Tower", type: "cadillac"),
    (name: "Push Thru Bar - Monkey", type: "cadillac"),
    (name: "Push Thru Bar - Teaser", type: "cadillac"),
    (name: "Push Thru Bar - Reverse Push Thru", type: "cadillac"),
    (name: "Push Thru Bar - Mermaid Sitting", type: "cadillac"),
    (name: "Push Thru Bar - Swan", type: "cadillac"),
    (name: "Push Thru Bar - Shoulder Roll Down", type: "cadillac"),
    (name: "Push Thru Bar - Push Thru", type: "cadillac"),
    (name: "Rollback Bar - Chest Expansion", type: "cadillac"),
    (name: "Rollback Bar - Thigh Stretch", type: "cadillac"),
    (name: "Rollback Bar - Long Back Stretch", type: "cadillac"),
    (name: "Rollback Bar - Rolling In and Out", type: "cadillac"),
    (name: "Stomach Massage", type: "cadillac"),
    (name: "Breathing", type: "cadillac"),
    (name: "Spread Eagle", type: "cadillac"),
    (name: "Pull Ups", type: "cadillac"),
    (name: "Hanging Pull Ups", type: "cadillac"),
    (name: "Twist Pull Ups", type: "cadillac"),
    (name: "Half Hanging", type: "cadillac"),
    (name: "Hanging Monkey on a Stick / Semi Circle", type: "cadillac"),
    (name: "Arm Springs - Squats", type: "cadillac"),
    (name: "Arm Springs - Hug", type: "cadillac"),
    (name: "Arm Springs - Boxing", type: "cadillac"),
    (name: "Arm Springs - Shaving", type: "cadillac"),
    (name: "Arm Springs - Butterfly", type: "cadillac"),
    (name: "Arm Springs - Side Arm", type: "cadillac"),
    (name: "Arm Springs - Fencing", type: "cadillac"),
    (name: "Rollback Bar - Standing", type: "cadillac"),
    (name: "Rollback Bar - Squats", type: "cadillac"),
    (name: "Rollback Bar - Side Arm", type: "cadillac"),
    (name: "Rollback Bar - Bicep Curls - (low hooks)", type: "cadillac"),
    (name: "Rollback Bar - zip up", type: "cadillac"),
    (name: "Ballet Stretches - Leg Stretches - Front", type: "cadillac"),
    (name: "Ballet Stretches - Leg Stretches - Back", type: "cadillac"),
    (name: "Ballet Stretches - Leg Stretches - Side", type: "cadillac")
]

let wundaChairExercises = [
    (name: "Footwork - Toes", type: "wundaChairChair"),
    (name: "Footwork - Arches", type: "wundaChair"),
    (name: "Footwork - Heels", type: "wundaChair"),
    (name: "Footwork - Tendon Stretch", type: "wundaChair"),
    (name: "Toes", type: "wundaChair"),
    (name: "Arches", type: "wundaChair"),
    (name: "Heels", type: "wundaChair"),
    (name: "Tendon Stretch", type: "wundaChair"),
    (name: "Push Down", type: "wundaChair"),
    (name: "Push Down One Arm", type: "wundaChair"),
    (name: "Pull Up", type: "wundaChair"),
    (name: "Spine Stretch Forward", type: "wundaChair"),
    (name: "Teaser - on Floor", type: "wundaChair"),
    (name: "Swan", type: "wundaChair"),
    (name: "Swan One Arm", type: "wundaChair"),
    (name: "Teaser - on Top", type: "wundaChair"),
    (name: "Mermaid - Seated", type: "wundaChair"),
    (name: "Arm Frog", type: "wundaChair"),
    (name: "Mermaid - Kneeling", type: "wundaChair"),
    (name: "Twist 1", type: "wundaChair"),
    (name: "Tendon Stretch", type: "wundaChair"),
    (name: "Table Top", type: "wundaChair"),
    (name: "Mountain Climb", type: "wundaChair"),
    (name: "Going Up Front", type: "wundaChair"),
    (name: "Going Up Side", type: "wundaChair"),
    (name: "Push Down One Arm", type: "wundaChair"),
    (name: "Side Pumping - Standing behind / Washer Woman", type: "wundaChair"),
    (name: "Frog - Facing Chair", type: "wundaChair"),
    (name: "Frog - Facing Out", type: "wundaChair"),
    (name: "Leg Press Down - Front", type: "wundaChair"),
    (name: "Backward Arms", type: "wundaChair"),
    (name: "Push Up - Top", type: "wundaChair"),
    (name: "Push Up - Bottom", type: "wundaChair"),
    (name: "Flying Eagle", type: "wundaChair")
]

let spineCorrectorExercises = [
    (name: "Arm - Circles", type: "spineCorrector"),
    (name: "Arm - One Arm Up/Down", type: "spineCorrector"),
    (name: "Arm - Hug", type: "spineCorrector"),
    (name: "Arm - Stretch with Bar", type: "spineCorrector"),
    (name: "Leg - Circles", type: "spineCorrector"),
    (name: "Leg - Small Circles", type: "spineCorrector"),
    (name: "Leg - Walking", type: "spineCorrector"),
    (name: "Leg - Beats", type: "spineCorrector"),
    (name: "Leg - Scissors", type: "spineCorrector"),
    (name: "Leg - Bicycle", type: "spineCorrector"),
    (name: "Leg - Frogs to V", type: "spineCorrector"),
    (name: "Leg - Helicopter", type: "spineCorrector"),
    (name: "Leg Circles Onto Head", type: "spineCorrector"),
    (name: "Shoulder Bridge", type: "spineCorrector"),
    (name: "Can Can/Hip Twist", type: "spineCorrector"),
    (name: "Leg - Rolling In and Out", type: "spineCorrector"),
    (name: "Teaser", type: "spineCorrector"),
    (name: "Hip Circles", type: "spineCorrector"),
    (name: "Swan", type: "spineCorrector"),
    (name: "Swimming", type: "spineCorrector"),
    (name: "Rocking", type: "spineCorrector"),
    (name: "Grasshopper", type: "spineCorrector")
]
